- bench/compress_numpy.py
- blosc2/__init__.py
- blosc2/blosc2_ext.pyx
- blosc2/utils.py
This is mainly for illustrative purposes.  Here are the speeds for compress/decompress on an M1-powered MacBook:
```
$ env PYTHONPATH=. python bench/compress_numpy.py
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
python-blosc2 version: 2.0.0-alpha
Blosc version: 2.0.0.beta.6.dev ($Date:: 2020-04-21 #$)
Compressors available: ['blosclz', 'lz4', 'lz4hc', 'zlib', 'zstd']
Compressor library versions:
blosclz: 2.3.0
lz4: 1.9.3
lz4hc: 1.9.3
zlib: 1.2.11.zlib-ng
zstd: 1.4.9
Python version: 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ]
Platform: Darwin-20.3.0-x86_64 (Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101)
Processor: i386
Byte-ordering: little
Detected cores: 8
Number of threads to use by …
```
> Example on how a copy can be avoided when decompressing numpy arrays

- blosc2/core.py
- examples/schunk.py
- tests/test_array.py
- tests/test_compress2.py
- tests/test_compressors.py
- tests/test_decompress.py
- tests/test_python_blosc.py
- tests/test_schunk.py
- tests/test_schunk_constructor.py
- tests/test_schunk_delete.py
- tests/test_schunk_insert.py
- tests/test_schunk_update.py
Update c-blosc2 submodule to support again a buffer size non divisible by the `cparams.typesize`, restore some tests with that condition and restore the `pack` function in order to use the type size of the object passed and obtain better compression results.
> Update submodule and restore support for #29

- .github/workflows/cibuildwheels.yml
Added aarch64 wheel build support.
@FrancescAlted Could you please review this PR?
> Add aarch64 wheel build support

- README.rst
- RELEASE_NOTES.md
- bench/pack_compress.py
- blosc2/SChunk.py
- blosc2/blosc2_ext.pyx
- blosc2/core.py
- examples/tutorial-basics.ipynb
This merely fixes simple typos.
There is room for further improvement, including in places where I have fixed typos, but that can be part of a different merge request:
* _different than_ ⤑ _different from_
* _Append a data data to the SChunk_ ⤑ _Append data to the SChunk_
* _object or bytearray to fill which length must be greater than 0_ ⤑ _object or bytearray to fill, the length of which must be greater than 0_
> Fix typos found by codespell

- tests/test_python_blosc.py
It is implicit under Python 3.
> Useless inheritance from object

- blosc2/blosc2_ext.pyx
Fixes segfaults during tests on Windows in "development mode".
The C pointer `storage.urlpath` was pointing to the value of a Python bytes instance, which got deleted while the pointer  was still in use.
I noticed that the return values of some C function calls are not checked for errors and c-blosc does not check some pointer arguments for NULL...
> Fix invalid pointer to urlpath argument

- doc/_static/css/custom.css
Looks like I forgot the styles to not show the navigation as external links in this project (we've got the same in c-blosc2 and python-blosc).
With this (and https://github.com/Blosc/blogsite/pull/7 which I'll merge after this one), all the work on having an integrated website with the docs should be complete. @martaiborra if you can have a quick look when you've got the time...
> Removing icon of external links in the navbar

- blosc2/SChunk.py
- blosc2/core.py
* The default mode for `open()` is `'r'`, a synonym of `'rt'`:
https://docs.python.org/3/library/functions.html#open
* `IOError` is kept for compatibility with previous versions; starting from Python 3.3, it is an alias of `OSError`:
https://docs.python.org/3/library/exceptions.html#IOError
* Directly yield from an iterable instead of iterating to yield items.
> Apply some pyupgrade suggestions

- tests/test_python_blosc.py
UTF-8 is the default encoding in Python 3, no need to define it explicitly any more:
```
```
> No need to define the encoding in Python 3

- blosc2/core.py
See:
https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module
> os.popen2 is deprecated → subprocess.run

- blosc2/__init__.py
- blosc2/core.py
* Use `min` builtin
* Iterate the dictionary directly instead of `.keys()`
> Apply DeepSource.io suggestions

- README.rst
Badge points to the wrong package on PyPI
> Fix PyPI Link in Readme Badge

- blosc2/__init__.py
- blosc2/blosc2_ext.pyx
- blosc2/ndarray.py
- blosc2/schunk.py
- doc/reference/ndarray_api.rst
- doc/reference/schunk_api.rst
- examples/ndarray/iterchunks_info.py
- tests/ndarray/test_iterchunks_info.py
This is a new chunk iterator optimized for retrieving metadata from chunks: cratio, whether they contain special values, and if so, which is the special value.
This is handy for iterating over datasets with a large number of chunks that are special; e.g. if some chunk is all made of zeros, it can be skipped during a reduction operation.  This can provide large speedups in e.g. sparse arrays (or arrays with lots of NaNs, or repeated values).
> Iterchunks info

- blosc2/blosc2_ext.pyx
Fixes segfault with a plugin that uses these params, such as blosc2_openhtj2k
> Initialize codec and filter params

- blosc2/blosc2_ext.pyx
- tests/test_ucodecs.py
- tests/test_ufilters.py
This lets use multithreading for user-defined plugins when the corresponding functions are not Python functions.
> Check multithreading only for python plugin functions

- bench/compress_numpy.py
After 0830349:
```
f-string: invalid conversion character: expected 's', 'r', or 'a'
```
> Fix error in 0830349

- bench/ndarray/transcode_data.py
- blosc2/core.py
- blosc2/ndarray.py
- tests/ndarray/test_copy.py
When iterating over a dictionary, we iterate over the keys.
> Remove redundant `.keys()`

- blosc2/schunk.py
It was probably thought as an optimisation in #79, but it's really a duplicate iteration.
> Avoid duplicate iteration over the same dict

- blosc2/core.py
This fixes a few issues with `blosc2.core.compute_partition`, the main one being that it may return some blockshapes which exceed the given maximum number of items (`nitems`) in certain cases. For instance, a maximum shape of 3x2 with a maximum `nitems` of 4 resulted in a blockshape of 3x2 (with 6 items). Quick code to test:
```python
from blosc2.core import compute_partition as cp
chunkshape = [3, 2]
blockitems0 = 4
#chunkshape = (10, 25, 50, 50)
#blockitems0 = 2048000 // 8
blockshape0 = [1 if cd == 1 else 2 for cd in chunkshape]
blockshape = compute_partition(blockitems0, blockshape0, chunkshape, True)
print(blockshape, math.prod(blockshape), '>?', blockitems0, chunkshape)
```
This does not fix the case where the initial blockshape already exceeds `nitems` (which should be unlikely). …
> Fix partition computation (i.e. blockshape from max nitems)

- blosc2/blosc2_ext.pyx
- blosc2/schunk.py
- tests/test_open.py
The new optional `offset` argument to `blosc2.schunk.open` allows providing an offset for Blosc2 super-chunks stored inside of other container files (like HDF5). Doc updates and a simple unit test are provided.
> Add optional offset to open function

- RELEASE_NOTES.md
- blosc2/__init__.py
- blosc2/blosc2_ext.pyx
- blosc2/core.py
- blosc2/ndarray.py
- tests/ndarray/test_ndarray.py
This allows serializing and deserializing NDArrays to/from contiguous in-memory frames.
Closes feature requests #114 and #146.
> New NDArray.to_cframe() method and blosc2.ndarray_from_cframe() function

- .pre-commit-config.yaml
- bench/compress_numpy.py
- bench/pack_compress.py
- bench/pack_tensor.py
- blosc2/core.py
- blosc2/info.py
- blosc2/ndarray.py
- examples/btune.py
- pyproject.toml
- tests/test_compress2.py
- tests/test_decompress.py
- tests/test_pathlib.py
- tests/test_ucodecs.py
- tests/test_ufilters.py
> `black`/`isort` → `ruff format`

- blosc2/core.py
`blosc2.open` supports `blosc2.decompress2`'s keywords argument, `nthreads`. However,  `blocs2.load_tensor` doesn't extend the functionality. 
Exposing `nthreads` will allow for faster tensors loading.
e.g.,
```python
blosc2.load_tensor(urlpath, nthreads=n)
```
> Add kwargs to `load_tensor`

- blosc2/blosc2_ext.pyx
- tests/test_vlmeta.py
All other vlmeta encoding/decoding code uses `blosc2_ext.encode/decode_tuple` to preserve tuple objects, but `vlmeta.to_dict()` in the extension was an exception:
```
>>> import blosc2
>>> a = blosc2.empty(shape=(10,10))
>>> a.schunk.vlmeta['l'] = [1,2,3]
>>> a.schunk.vlmeta['t'] = (1,2,3)
>>> a.schunk.vlmeta['l']
[1, 2, 3]
>>> a.schunk.vlmeta['t']
(1, 2, 3)
>>> a.schunk.vlmeta.to_dict()
{b'l': [1, 2, 3], b't': ['__tuple__', 1, 2, 3]}
```
This fixes the issue and performs some minor extra testing for list and tuple encoding.
> Fix vlmeta.to_dict not honoring tuple encoding

- blosc2/core.py
Unless I am missing something, there's no need to duplicate:
https://github.com/Blosc/python-blosc2/blob/4fcc352e76ec554c934e7fab959af6a1238bff63/blosc2/core.py#L15
> Avoid multiple imports of numpy

- bench/ndarray/eval_expr_numba.py
- blosc2/lazyexpr.py
- blosc2/ndarray.py
This adds a benchmark for comparing the new evaluation engine with numexpr and numba.  Here it is the result on my MacBook Air with M1:
```
NumPy took 0.043 s
NumExpr took 0.041 s
Blosc2+numexpr took 0.109 s
Numba took 0.022 s
Blosc2+numba+eval took 0.135 s
Blosc2+numba+getitem took 0.210 s
```
Currently the getitem method is 1.6x slower than .eval(), but in the future it would be nice to see whether the reimplementation using postfilters (instead of prefilters) would lead to better performance or not.
> Benchmark for udf numba

- blosc2/__init__.py
- blosc2/lazyexpr.py
- doc/reference/lazyarray.rst
- examples/ndarray/general_expressions.py
- tests/ndarray/test_lazyexpr.py
This allows to build expressions that contains all operands as numpy arrays.  Also has an `out=` param for allowing to store the output of the evaluation there (although both options at the same time are not supported yet).  E.g.:
```
operands = {"a1": na1, "a2": a2}
out = np.array_like(na1)
expr = blosc2.lazyexpr("a1 + a2", operands=operands, out=out)
res = expr.eval()
assert out is res
```
> New lazyexpr() constructor

- blosc2/core.py
- blosc2/lazyexpr.py
- tests/ndarray/test_lazyexpr.py
- tests/ndarray/test_lazyexpr_fields.py
- tests/ndarray/test_reductions.py
By returning results of reductions as numpy arrays, users will receive the expected output in their workflows.  The drawbacks are that the data returned is uncompressed (numpy array), so it will take more space in memory, and that the user cannot specify the result to be on-disk.
This decision is justified not only by convenience, but also by the fact that reduced data should, in general, take (much) less space than regular NDArrays.  That should be enough for most of use cases.  For the rest, one could add a new `out` parameter (or `kwargs` for the NDArray properties, to be discussed) to the reduction functions in the future. 
Finally, this PR also enables expressions coming from the fusion of other expressions to be new instances.  This facilitates expression handling, as this is the …
> Reductions now output numpy arrays

- blosc2/__init__.py
- blosc2/c2array.py
- blosc2/lazyexpr.py
- doc/reference/c2array.rst
- tests/ndarray/test_c2array_expr.py
- tests/ndarray/test_c2array_reductions.py
- tests/ndarray/test_c2array_udf.py
- tests/test_open.py
This adds the context manager `c2context` which allow setting a default value for the Caterva2 subscriber URL base and authorization cookie, to be used when a particular instance of `C2Array` does not have a set one. Note that the subscriber URL base is now optional both in `URLPath` and `C2Array.__init__`.
Context managers may be invoked arbitrarily inside one another and their values will stack, inheriting those set by the previous ones. Concurrent entering and exiting of the context managers is not supported, though, as they use a private global variable in the `blosc2.c2array` module.
Also, when no subscriber URL base is set in the `C2Array` instance nor via the context manager, code defaults to querying the `BLOSC_C2URLBASE` environment variable. If no default URL base is set …
> Caterva2 context managers

- blosc2/c2array.py
- tests/conftest.py
- tests/ndarray/test_c2array_expr.py
- tests/ndarray/test_c2array_reductions.py
- tests/ndarray/test_c2array_udf.py
- tests/test_open.py
This extends `blosc2.c2context()` with `username` and `password` parameters. When they are provided, the context manager performs a login to the Caterva2 subscriber and uses the returned authorization token for subsequent operations. Their default values may be specified via the `BLOSC_C2USERNAME` and `BLOSC_C2PASSWORD` environment variables.
Tests fixtures have been rewritten to ease enabling authentication for relevant `C2Array` tests. A new test has been added which explicitly checks opening such an array with authentication (by creating a throwaway user at the subscriber).
Some fixes to the semantics and documentation for parameter inheritance and defaults for the context manager are included too.
> Login support for Caterva2 context manager

- blosc2/__init__.py
SIM401 Use `self.get(..., ...)` instead of an `if` block
> Enforce ruff/flake8-simplify rule SIM401

- blosc2/lazyexpr.py
Python will implicitly return `None`.
> Remove useless single `return` at end of function

- blosc2/lazyexpr.py
At the very least catch `Except` instead of the default `BaseExcept`, thus not catching:
- `BaseExceptionGroup`,
- `GeneratorExit`,
- `KeyboardInterrupt`,
- `SystemExit`.
> Do not use bare `except`

- blosc2/lazyexpr.py
- blosc2/ndarray.py
- blosc2/schunk.py
This is a breaking change: `TypeError` is raised instead of `ValueError`.
> Enforce some ruff/tryceratops rules (TRY)

- blosc2/__init__.py
- blosc2/core.py
- blosc2/lazyexpr.py
This allows to perform read-ahead of operands on disk while doing operations.  This can dramatically accelerate out-of-core computations up to 2x (!).
> Read ahead

- doc/getting_started/tutorials/02.ndarray-basics.ipynb
NPY002 Replace legacy `np.random.normal` call with `np.random.Generator`
Fixes #241.
> Apply ruff NumPy-specific rule NPY002

- .github/workflows/build.yml
- .github/workflows/cibuildwheels.yml
- .gitignore
- .gitmodules
- CMakeLists.txt
- README.rst
- RELEASING.rst
- doc/getting_started/installation.rst
Do not use c-blosc2 as a submodule anymore and use the `FetchContent` feature of CMake instead.  Suggested by @LecrisUT .
> Fetch content

- src/blosc2/lazyexpr.py
Replace `range(len(expr))` with `enumerate(expr)`
> Implicit enumerate call

- src/blosc2/helpers.py
This PR fixes issue #276 
Python 3.13 automatically [strips leading whitespace in docstrings](https://docs.python.org/3.13/whatsnew/3.13.html#other-language-changes) for performance reasons which makes the `_inherit_doc_parameter()` decorator fail.
I tested the fix on Python 3.12 and Python 3.13.rc3. Generated docs look good.
> Fix doc inheritance for Python 3.13

- src/blosc2/lazyexpr.py
PLR1733 Unnecessary lookup of dictionary value by key
> Apply ruff/Pylint rule PLR1733

- .flake8
- bench/fill_special.py
- bench/io.py
- bench/ndarray/eval_expr_numba.py
- bench/ndarray/reduce_expr.py
We may need a ruff equivalent to `max-complexity = 10`.
> flake8 is not used any more

- examples/ndarray/reduce_and_enlarge.py
- requirements-dev.txt
- src/blosc2/lazyexpr.py
- tests/ndarray/test_reductions.py
Also fix all pre-commit issues, again, so that CI tests pass.
> black and isort are not used any more (again)

- pyproject.toml
- src/blosc2/core.py
- src/blosc2/lazyexpr.py
- src/blosc2/ndarray.py
- src/blosc2/schunk.py
- tests/ndarray/test_lazyexpr.py
- tests/test_open.py
- tests/test_prefilters.py
Fixes #310.
Use the default value of the maximum McCabe complexity: 10
It looks like some functions became too complex after disabling flake8. How to handle that? Modify these functions? Disable `C901` for these functions?
> Enforce ruff/mccabe rule (C90)

- examples/ndarray/reduce_and_enlarge.py
- src/blosc2/lazyexpr.py
- src/blosc2/ndarray.py
- src/blosc2/proxy.py
- tests/ndarray/test_lazyexpr.py
- tests/ndarray/test_lazyexpr_fields.py
- tests/ndarray/test_setitem.py
This PR enhances the dtype inference so that it mimics now more NumPy than the numexpr one.  Although perfect adherence to NumPy casting conventions is not there yet, it is a big step forward towards better compatibility with NumPy.  In particular, support for e.g. 'a + np.int8(1)'  string expressions allows to serialize them, while keeping NumPy type inference when expression is re-opened from disk.
Most of the `np.int`, `np.float`, `np.str` and `np.bytes` casting funcs for constants are supported.
> Type inference that is closer to NumPy

- examples/ndarray/filter_sort_fields.py
- src/blosc2/lazyexpr.py
- src/blosc2/ndarray.py
- tests/ndarray/test_getitem.py
- tests/ndarray/test_lazyexpr.py
- tests/ndarray/test_lazyexpr_fields.py
This allows performing data filtering, as well as sorting, in structured NDArrays.  For example, given an array `sarr` with fields 'a', 'b' and 'c', the next:
```
farr = sarr["b >= c"].sort("c").indices().compute()
```
puts in `farr` the indices of the rows that fulfills that values in fields in 'b' are larger than values in 'c' (`"b >= c"` above), sorted by column 'c'.
`farr` is in turn an NDArray, so it is compressed; think of it as a compact index for other tasks.
See the new ``examples/ndarray/filter_sort_fields.py`` self-contained script.
> Filter and sort fields

- pyproject.toml
> ### [Removal of six deprecated rules](https://astral.sh/blog/ruff-v0.8.0#removal-of-six-deprecated-rules)
> 
> Six rules have been removed in this release. We realized that the changes they were asking users to make to their code were either unnecessary or outright undesirable:
> * [`missing-type-self`](https://docs.astral.sh/ruff/rules/missing-type-self/) (`ANN101`) and [`missing-type-cls`](https://docs.astral.sh/ruff/rules/missing-type-cls/) (`ANN102`) have both been removed from our [`flake8-annotations`](https://docs.astral.sh/ruff/rules/#flake8-annotations-ann) category. Both have been deprecated since [Ruff 0.2.0](https://astral.sh/blog/ruff-v0.2.0).
> * [`pytest-missing-fixture-name-underscore`](https://docs.astral.sh/ruff/rules/pytest-missing-fixture-name-underscore/) (PT004) …
> Deprecated rules have been removed from ruff 0.8.0

- doc/reference/index.rst
- doc/reference/lazyarray.rst
- doc/reference/low_level.rst
- doc/reference/utilities.rst
- src/blosc2/__init__.py
- src/blosc2/core.py
- src/blosc2/lazyexpr.py
- tests/ndarray/test_evaluate.py
- tests/ndarray/test_jit.py
This emulates `numexpr.evaluate()`, but with the next improvements:
1) Use more functionality (e.g. reductions) than numexpr.
2) Follow casting rules of NumPy more closely.
3) Use both NumPy arrays and Blosc2 NDArrays in the same expression.
As NDArrays can be on-disk, the expression can be evaluated without loading
the whole array into memory (i.e. using an out-of-core approach).
> blosc2.evaluate()

- .github/workflows/wasm.yml
- pyproject.toml
- src/blosc2/__init__.py
- src/blosc2/c2array.py
- src/blosc2/core.py
- src/blosc2/lazyexpr.py
- src/blosc2/ndarray.py
- tests/conftest.py
- tests/ndarray/test_c2array_expr.py
- tests/ndarray/test_c2array_reductions.py
- tests/ndarray/test_evaluate.py
- tests/ndarray/test_full.py
- tests/ndarray/test_lazyexpr.py
- tests/ndarray/test_lazyexpr_fields.py
- tests/ndarray/test_nans.py
- tests/ndarray/test_proxy_expr.py
- tests/ndarray/test_reductions.py
- tests/ndarray/test_zeros.py
Still preliminary, but most of the tests should be passing already.
> Support for building WASM32 wheels

- bench/ndarray/jit-expr.py
- bench/ndarray/jit-numpy-funcs.py
- bench/ndarray/jit-reduc.py
- examples/ndarray/jit-numpy-funcs.py
- src/blosc2/blosc2_ext.pyx
- src/blosc2/core.py
- src/blosc2/lazyexpr.py
- src/blosc2/ndarray.py
- tests/ndarray/test_evaluate.py
- tests/ndarray/test_full.py
- tests/ndarray/test_lazyexpr.py
- tests/ndarray/test_nans.py
This implements the array interface to array containers.  This allows evaluating blosc2 containers with numpy functions, like:
```
@blosc2.jit
def expr_jit(a, b, c):
return np.cumsum(((a**3 + np.sin(a * 2)) < c) & (b > 0), axis=0)
```
In this case, `np.cumsum` is not implemented in blosc2 as a function, but the array interface automatically converts the LazyArray into a numpy ndarray, and proceeds with the computation.  This requires a conversion, but in exchange, we have access to all the functions in numpy seamlessly.
> Array interface

- tests/ndarray/test_getitem.py
- tests/ndarray/test_lazyexpr_fields.py
Although that's not the case here, the variable will be undefined if the list is empty.
> Avoid using loop variable outside the loop

- src/blosc2/lazyexpr.py
To reproduce:
blosc2.open('path-to-lazy-expression-with-missing operands')
With this change it still tries to guess the dtype and the shape, but this either fails with an error or makes the wrong guess. Because with missing operands it's imposible to correctly find out the dtype and shape, in this case dtype and shape should be None (this remains to be done).
There should be an error when trying to evaluate the expression, but not when opening it, because we may want to inspect it.
> open lazyexpr don't fail if missing operands (wip)

- bench/ndarray/array-constructor-memray.py
- bench/ndarray/array-constructor.py
- src/blosc2/blosc2_ext.pyx
- src/blosc2/lazyexpr.py
- src/blosc2/ndarray.py
arange() and linspace() constructors should be better now, as they do not require temporaries.
This is still work in progress.
> New version for reducing memory consumption

- src/blosc2/lazyexpr.py
- tests/ndarray/test_lazyexpr.py
Forcibly add parenthesis on creation of lazyexpr via strings to ensure order-of-operations respected and smaller lazy expressions which compose a larger lazyexpr are executed first.
Also remove unnecessary data type modification of already-existing lazyexpr when creating new lazy expression based on this already-existing lazyexpr.
> Enable chaining of lazy expressions for logical operators

- src/blosc2/lazyexpr.py
- tests/ndarray/test_lazyexpr.py
Parentheses are now only added (recursively) to an expression when one uses it to form other expressions. Saving and reloading the expression preserves the original user-provided expression.
> Change parethesis handling

- src/blosc2/lazyexpr.py
- tests/ndarray/test_reductions.py
Fix bug introduced in #402 that added extra dimension due to None indexing for reductions. Extended test to check that dimensions are correct. Solves https://github.com/ironArray/Caterva2/issues/179
> Fix incorrect appending of dim to computed reductions

- pyproject.toml
- src/blosc2/lazyexpr.py
- tests/ndarray/test_lazyexpr.py
Expand possibilities for chaining string-based lazy expressions to include main operand types (LazyExpr and NDArray). Have to incorporate other data types (which do not have shape attribute, e.g. int, float etc.) in future PR - see #406 .
> Fix chaining

- src/blosc2/ndarray.py
- tests/ndarray/test_evaluate.py
- tests/ndarray/test_jit.py
- tests/ndarray/test_ndarray.py
Fixes #405, which failed silently when num and shape were not compatible. Now handles the four cases:
- shape = None, num = None -> Error
- shape = None, num = value -> shape = (value,)
- shape = value, num = None -> num= prod(shape)
- shape = valueA, num = valueB -> Error if valueB!= prod(valueA), else proceed
> Fix linspace for incompatible num/shape

- src/blosc2/schunk.py
Minor documentation update originating from [this comment](https://github.com/Blosc/python-blosc2/commit/c097f2d969d6a916dfafbe62df296c71b4380290).
> Add clarification about unsupported mode in docs of blosc.open

- src/blosc2/lazyexpr.py
- tests/ndarray/test_lazyexpr.py
- tests/ndarray/test_lazyexpr_fields.py
To enable use of where in string lazyexprs, added code to correctly compile string to be passed to numexpr.
Secondly, added check in lazyexpr.dtype to allow for operands (e.g int) which do not have shape attribute. This means that chaining lazyexprs is more fully supported (see test), and so fixes #406.
> Allow use of where for string expressions and integer operands

- src/blosc2/lazyexpr.py
- tests/ndarray/test_reductions.py
Solves #412. For []-indxeing, converts internally to .slice to avoid decompressing and then recompressing for .compute function.
> Add slicing to string lazyexprs

- src/blosc2/lazyexpr.py
- tests/ndarray/test_reductions.py
Since np.s_[1] does not return a slice object, but rather an integer, the code failed for cases such as this. Now fixed.
> Fixed bug for integer indexes

- src/blosc2/lazyexpr.py
- tests/ndarray/test_reductions.py
Resolves #415. The problem was in the conserve_functions function when looping over the operands of a lazyexpr which contains operands already labelled using the o- convention. Adding an illegal character to keep track of already changed operands, and then removing, solves the problem.
> Fix lazyexpr o0 bug to pass test

- src/blosc2/lazyexpr.py
- tests/ndarray/test_lazyexpr.py
Add .slice method to LazyExpr class so that it is possible to get a slice and return a blosc2.NDArray (__getitem__ returns NumPy array).
> Enable slice lazy

- src/blosc2/proxy.py
- tests/test_pandas_udf_engine.py
Closes #383 
With these changes, it'll be possible to do things like this with pandas and blosc2:
```python
import pandas
import blosc2
def my_func(x):
return np.sin(x * 2)
s = pandas.Series([1, 2, 3], index=list('abc'), name='sample')
print(s.map(my_func, engine=blosc2.jit))
```
In this PR I'm assuming that `blosc2.jit` is intended to be used with vectorized numpy operations. If that's not the case, and you want to support scalar functions and jit Python loops (see example below), let me know and we can implement this for map:
```python
@blosc2.jit
def my_func(array):
for item in array:
scalar_udf(item)
```
Also, `apply` is designed in pandas to call the udf for each column or row in a dataframe. I'm passing the whole array since it's a numpy array and I think operations should be …
> Add support for new pandas UDF engine

- examples/ndarray/lazyexpr_where_indexing.py
- src/blosc2/lazyexpr.py
- tests/ndarray/test_lazyexpr_fields.py
As discussed in #399, there were problems for slicing lazy expressions with one where condition, since the output is in general of a different length to the input.
The .compute function when provided with a slice argument internally takes slices of the operands prior to evaluating the expression. One could change this, but I think it is better to interpret the argument as slicing operands prior to calculation. If one is interested in a general slice of the full result one can always force via expr.compute().slice(sl). 
An unfortunate consequence is that the syntax of the get_item method is a little misleading (hence why I have changed the tests).
expr.compute(sl)[:] is equal to the numpy syntax nsa1[sl][ne_evaluate(expr)[sl]].
> Make behaviour of compute consistent for slicing

- src/blosc2/ndarray.py
- tests/ndarray/test_concatenate.py
When writing to disk, first concatenate must be in write mode, but afterwards in read/write mode.
> Improve mode handling for concatenating to disk

- bench/ndarray/slice-expr.py
- src/blosc2/__init__.py
- src/blosc2/lazyexpr.py
- tests/ndarray/test_lazyexpr.py
The new `slices_eval_getitem()` internal function allows to evaluate things like:
```python
d = 200
shape = (d,) * 4
chunks = (d // 4,) * 4
blocks = (d // 10,) * 4
a = blosc2.ones(shape=shape, chunks=chunks, blocks=blocks)
expr = a * 2
t = time.time()
res = expr[:,:,:,1]
t3 = time.time() - t
```
more efficiently, so that t3 can be up to 10x faster than with existing code.
The solution is partial because this only works for `expr[:,:,:,1]` idiom, and not `expr.compute(item=...)`.  Also, memory handling for operand temporaries has changed: now all the operands will use the final slice prior to do the computation.  While for the case above this is (very) beneficial, this should not be the case in general.
I tried to assemble a more general solution in the new `slices_eval2()`, but it is not …
> New slices_eval_getitem() for accelerating evals with __getitem__

- src/blosc2/lazyexpr.py
- src/blosc2/ndarray.py
- tests/ndarray/test_lazyexpr.py
- tests/ndarray/test_reductions.py
Now support steps for reductions. More complex slicing operations also now give correct answers. The new step_handler function could be incorporated into slice_eval to avoid numpy arrays completely and only use final_slice to get rid of dummy dimensions.
> Fixing reductions and slicing for lazy expressions

- doc/getting_started/tutorials/06.remote_proxy.ipynb
- examples/ndarray/c2array_expr.py
- examples/ndarray/proxy-carray.py
- src/blosc2/c2array.py
This migrates from old `demo.caterva2.net` demo site to new `cat2.cloud/demo` one.  The tests still need to be migrated, but this should be done in another PR.
> Update to cat2cloud

- .pre-commit-config.yaml
- README.rst
- pyproject.toml
```console
$ ruff check
warning: The following rules have been removed and ignoring them has no effect:
- UP038
All checks passed!
$ 
```
Supersedes #470.
> Update ruff pre-commit hook

- tests/ndarray/test_elementwise_funcs.py
The new `test_elementwise_funcs.py` module uses around 40s on my (relatively modern) laptop.  This PR allows to mark some tests as 'heavy'. After that:
```bash
> pytest tests/ndarray/test_elementwise_funcs.py
<snip>
============================================== 878 passed, 10 skipped, 444 deselected, 10 warnings in 9.71s ==============================================
```
```bash
> pytest tests/ndarray/test_elementwise_funcs.py -m heavy
============================================== 438 passed, 6 skipped, 888 deselected, 6 warnings in 30.04s ===============================================
```
which is more manageable, and compliant with the existing convention of marking heavy tests as 'heavy'.
> Separate heavy tests in element wise testing

- src/blosc2/core.py
Added information about setting thread counts via environment variables.
> Update documentation for thread management

- ADD_LAZYFUNCS.md
- src/blosc2/lazyexpr.py
- src/blosc2/linalg.py
- src/blosc2/ndarray.py
- src/blosc2/shape_utils.py
- tests/ndarray/test_lazyexpr.py
- tests/ndarray/test_lazyudf.py
- tests/ndarray/test_linalg.py
- tests/ndarray/test_reductions.py
Although there was no double evaluation in old versions of blosc2 for reductions as there was an ``is_inside_new_expr()`` stack check which aborted the evaluation and returned ``blosc2.zeros`` during the ``eval`` call, we have added a shape parser to avoid having to arrive at ``reduce_slices`` for reductions. In addition, this allows us to handle other non-numexpr functions without adding the same ``is_inside_newexpr()`` call. 
This PR is thus useful since 1) it adds the possibility to compute with arbitrary blosc2 functions (such as ``matmul`` or even ``logaddexp``) in a lazy imperative way via the changes to ``ne_evaluate`` and 2) adds a reasonably extensive shape parser function, which is a bit more explicit than the returning ``blosc2.zeros`` hack.
For the following benchmark:
``` …
```
> Add general lazy evaluation for all blosc2 functions

- src/blosc2/lazyexpr.py
- src/blosc2/ndarray.py
- src/blosc2/proxy.py
- tests/ndarray/test_lazyudf.py
> Improve inheritance
