- bench/compress_numpy.py
- blosc2/__init__.py
- blosc2/blosc2_ext.pyx
- blosc2/core.py
- examples/compress2_decompress2.py
- examples/schunk.py
- tests/test_compress2.py
- tests/test_compressors.py
- tests/test_python_blosc.py
- tests/test_schunk.py
- tests/test_schunk_constructor.py
- tests/test_vlmeta.py
This PR introduces new `Codec` and `Filter` Enum classes.  This is handier for the users to check for available filters and codecs.
> Filter and codec enums

- bench/compress_numpy.py
- bench/pack_compress.py
- setup.py
- tests/test_python_blosc.py
Get rid of code specific to Python 2.
> Python 2 is not supported

- bench/pack_compress.py
- bench/pack_tensor.py
- blosc2/__init__.py
- blosc2/core.py
- doc/reference/top_level.rst
- requirements-tests.txt
- tests/test_array.py
Support for serializing PyTorch and TensorFlow tensors.
> Pack tensor

- CMakeLists.txt
- blosc2/CMakeLists.txt
> Consistency between python-blosc and python-blosc2

- blosc2/core.py
> Fix os_release_pretty_name when os-release does not exists

- README.rst
583e2df 
`requirements.txt` → `requirements-build.txt`
> Update documentation to match past change 583e2df

- blosc2/__init__.py
- blosc2/blosc2_ext.pyx
- blosc2/core.py
- blosc2/ndarray.py
- examples/ndarray/ex_buffer.py
- examples/ndarray/ex_copy.py
- examples/ndarray/ex_getitem.py
- examples/ndarray/ex_meta.py
- examples/ndarray/ex_numpy.py
- examples/ndarray/ex_persistency.py
- examples/ndarray/ex_resize.py
- requirements-runtime.txt
- tests/ndarray/test_buffer.py
- tests/ndarray/test_copy.py
- tests/ndarray/test_empty.py
- tests/ndarray/test_full.py
- tests/ndarray/test_getitem.py
- tests/ndarray/test_setitem.py
- tests/ndarray/test_zeros.py
- tests/test_comp_info.py
This should allow to make `chunks` and `blocks` in constructors optional.
> Automatic guesses for chunk and block partitions

- blosc2/CMakeLists.txt
Fixes #15, based on https://github.com/Blosc/python-blosc2/commit/a1e419ddc9773ab6cc80c397e39935e9b6b76ded by @ArchangeGabriel.
> Allow linking to system c-blosc2 shared library

- .github/workflows/build.yml
- .github/workflows/cibuildwheels.yml
- requirements-tests.txt
Bu using conda-forge package for ndindex, GHA tests seems to work again.
> Workaround for ndindex issues with wheels on Win32

- .github/workflows/cibuildwheels.yml
- RELEASING.rst
- pyproject.toml
- requirements-build.txt
- setup.py
Fixes #110
Fixes #105 (to the extend that scikit-build allows it at the present time)
> Remove pkgconfig/blosc2.pc from python installation

- CMakeLists.txt
- blosc2/blosc2_ext.pyx
- tests/test_compress2.py
- tests/test_compressors.py
- tests/test_decompress.py
- tests/test_schunk_insert.py
- tests/test_schunk_update.py
Adapt to the recent BTune fixes and improvements in C-Blosc2
> BTune fixes

- blosc2/__init__.py
- blosc2/blosc2_ext.pyx
- blosc2/core.py
- doc/reference/autofiles/top_level/blosc2.Tuner.rst
- doc/reference/top_level.rst
- examples/btune.py
With this PR now you can specify the tuner to use like you would do with the codec.
> Add tuner parameter in cparams

- blosc2/core.py
- tests/ndarray/test_empty.py
> Check that chunks/blocks computation does not allow a 0 in blocks

- blosc2/lazyexpr.py
- blosc2/ndarray.py
- tests/ndarray/test_lazyexpr.py
This is still work in progress
> First introduction of pow operator

- .github/workflows/build.yml
- blosc2/__init__.py
- blosc2/blosc2_ext.pyx
- blosc2/c2array.py
- blosc2/lazyexpr.py
- blosc2/ndarray.py
- doc/reference/c2array.rst
- doc/reference/index.rst
- examples/ndarray/c2array_expr.py
- requirements-runtime.txt
- tests/ndarray/test_c2array.py
- tests/ndarray/test_c2array_expr.py
- tests/ndarray/test_c2array_reductions.py
- tests/ndarray/test_c2array_udf.py
- tests/ndarray/test_lazyexpr.py
Support for remote arrays as C2Array. This object can work with expressions, udf and reductions.
> Add support for remote arrays

- tests/test_open.py
UP031 Use format specifiers instead of percent format
> Enforce ruff/pyupgrade new rule UP031

- tests/ndarray/test_lazyexpr.py
Replace redundant list comprehension with generator.
> Remove useless list brackets

- blosc2/lazyexpr.py
`None` is the default value by default, this is redundant.
> Unnecessary None provided as default

- tests/ndarray/test_reductions.py
Use `is` or `isinstance` instead.
> Do not use `==` when comparing types

- blosc2/c2array.py
- blosc2/ndarray.py
- blosc2/schunk.py
- doc/getting_started/tutorials/00.schunk-basics.ipynb
- doc/getting_started/tutorials/01.schunk-slicing_and_beyond.ipynb
- doc/getting_started/tutorials/02.ndarray-basics.ipynb
- doc/getting_started/tutorials/03.lazyarray-expressions.ipynb
- doc/getting_started/tutorials/03.lazyarray-udf.ipynb
- doc/getting_started/tutorials/10.ucodecs-ufilters.ipynb
- doc/getting_started/tutorials/11.prefilters.ipynb
- doc/getting_started/tutorials/12.postfilters.ipynb
- tests/conftest.py
- tests/ndarray/test_auto_parts.py
- tests/ndarray/test_c2array_expr.py
- tests/ndarray/test_c2array_reductions.py
- tests/ndarray/test_c2array_udf.py
- tests/ndarray/test_lazyexpr.py
- tests/ndarray/test_lazyexpr_fields.py
- tests/ndarray/test_ndarray.py
- tests/ndarray/test_proxy_c2array.py
- tests/ndarray/test_proxy_expr.py
- tests/ndarray/test_reductions.py
- tests/test_decompress.py
- tests/test_proxy_schunk.py
- tests/test_python_blosc.py
Most importantly:
* [Jupyter notebooks are now linted and formatted by default](https://astral.sh/blog/ruff-v0.6.0#jupyter-notebooks-are-now-linted-and-formatted-by-default)
> Start applying ruff 0.6

- src/blosc2/core.py
- src/blosc2/lazyexpr.py
Rewrite as a list comprehension.
> Unnecessary generator

- README.rst
Improve rendering of README.rst.
> README rendering

- src/blosc2/ndarray.py
C419 Unnecessary list comprehension
> Apply ruff/flake8-comprehensions rule

- src/blosc2/ndarray.py
> Unused variable

- src/blosc2/lazyexpr.py
- src/blosc2/ndarray.py
- tests/ndarray/test_reductions.py
Solves #397. Also allows one to add arbitrary numbers of newaxes via indexing using ``None`` (as in NumPy).
> Fix indexing for lazy expressions, and allow use of None in getitem

- .pre-commit-config.yaml
Changes:
```
ruff (legacy alias)......................................................Passed
```
into:
```
ruff check...............................................................Passed
```
> Update pre-commit ruff legacy alias

- pyproject.toml
- src/blosc2/lazyexpr.py
- src/blosc2/ndarray.py
Incorporate changes from numexpr version 2.13.1. Also cleanup up ufuncs a bit
> Remove addbool
